name: guita
description: App móvil para medición de consumo de agua (Güita).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  flutter_riverpod: ^3.0.3
  lottie: ^3.1.2
  fl_chart: ^0.69.2
  intl: ^0.19.0
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Croogla
      fonts:
        - asset: assets/fonts/Croogla.ttf
